---
trust-domain: adhoc

task-priority: lowest

taskgraph:
    register: adhoc_taskgraph:register
    repositories:
        # This is the manifest repo
        adhoc-manifest:
            name: "Adhoc manifest"
            project-regex: adhoc-manifest$
            default-repository: https://github.com/mozilla-releng/adhoc-manifest
            default-ref: master
            ssh-secret-name: project/adhoc/adhoc-github-clone-ssh
            type: git
        adhoc-stage:
            # string: the name of the repo, for humans
            name: "Adhoc Stage"
            project-regex: mvp-adhoc$
            default-repository: https://github.com/mozilla-releng/mvp-adhoc
            default-ref: master
            type: git
    cached-task-prefix: adhoc

workers:
    aliases:
        b-linux:
            provisioner: adhoc-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: adhoc-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: adhoc-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": adhoc-3-signing
                    default: adhoc-t-signing
        shipit:
            provisioner: scriptworker-k8s
            implementation: scriptworker-shipit
            os: scriptworker
            worker-type:
                by-level:
                    "3": adhoc-3-shipit
                    default: adhoc-t-shipit

notify:
    email:
        - aki+mvp-adhoc@mozilla.com
    prefix: "[adhoc-stage]"

release-promotion:
    flavors:
        promote:
            target-tasks-method: promote_adhoc

private-artifact-prefix: releng/adhoc

scriptworker:
    scope-prefix: project:adhoc:releng
