---
trust-domain: adhoc

task-priority: lowest

taskgraph:
    register: adhoc_taskgraph:register
    repositories:
        # This is the manifest repo
        adhoc:
            # string: the name of the repo, for humans
            name: "Adhoc manifest"
            # regex: to match the base name of the repo
            project-regex: adhoc-manifest
            # string: the repo url. Use `git@github.com:org/repo` for private
            #         repositories.
            default-repository: https://github.com/mozilla-extensions/adhoc-manifest
            # string: which branch is primary; should be `master`
            default-ref: master
            # enum: hg or git; should be `git`
            type: git
    cached-task-prefix: adhoc

workers:
    aliases:
        b-linux:
            provisioner: adhoc-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: adhoc-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: adhoc-t-signing-dev
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": adhoc-3-signing
                    default: adhoc-t-signing-dev

github_clone_secret: project/adhoc/adhoc-github-clone-ssh

scriptworker:
    scope-prefix: project:adhoc:releng
