# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.docker_image:transforms
    - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.task:transforms

jobs:
    debian10-raw:
        definition: debian-raw
        args:
            BASE_IMAGE: debian:buster-20191014
            DIST: buster
            SNAPSHOT: '20191014T205056Z'
    fetch:
        definition: fetch
        parent: debian10-raw
        packages:
            - deb10-python-zstandard
