# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.cached_tasks:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    worker-type: b-linux
    worker:
        max-run-time: 1800
    run-on-projects: []
    run:
        dist: wheezy
        snapshot: 20171210T214726Z

jobs:
    deb10-python-zstandard:
        description: "python-zstandard for Debian buster"
        run:
            using: debian-package
            dist: buster
            tarball:
                url: https://github.com/indygreg/python-zstandard/archive/0.11.1.tar.gz
                sha256: 2df90698e22f0da49cdd360438479f363e58eb8c3ac6e8bac84d831cf8e7baf4
            name: python-zstandard
            pre-build-command: debchange -v 0.11.1-1.deb10moz --distribution buster "Mozilla backport for buster"
